[package]
name = "liquidation_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.9", features = ["provider-ws", "sol-types", "contract", "transport-ws"] }
clap = { version = "4.5.39", features = ["derive"] }
eyre = "0.6.12"
ndarray = "0.16.1"
start = "0.4.4"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
